### ISSUE TITLE
Suggestion: Add PDF object for rulebook

### ISSUE THREAD

**Issue by vyder** [ikegami/tts_brass#1]
That object makes it a lot easier to read than the one that is currently in the `Kini20210103` version of the game.

Something like this:

**BirminghamRulesPDF.json:**
```
{
  "SaveName": "",
  "GameMode": "",
  "Date": "",
  "Gravity": 0.5,
  "PlayArea": 0.5,
  "GameType": "",
  "GameComplexity": "",
  "Tags": [],
  "Table": "",
  "Sky": "",
  "Note": "",
  "Rules": "",
  "TabStates": {},
  "ObjectStates": [
    {
      "Name": "Custom_PDF",
      "Transform": {
        "posX": 9.0,
        "posY": 1.46963024,
        "posZ": 22.0000343,
        "rotX": -2.13162082E-07,
        "rotY": 179.989548,
        "rotZ": -1.50791077E-08,
        "scaleX": 2.0,
        "scaleY": 1.0,
        "scaleZ": 2.0
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomPDF": {
        "PDFUrl": "http://files.roxley.com/Brass-Birmingham-Rulebook-2018.11.20-highlights.pdf",
        "PDFPassword": "",
        "PDFPage": 8,
        "PDFPageOffset": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "GUID": "0babcf"
    }
  ],
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": "",
  "VersionNumber": ""
}
```

**Comment by ikegami** [comment]
You know you can use PgUp and PgDn with the existing object?
You know you can use page numbers ("1", "2", etc) with the existing object?

And Alt works better with tiles than PDF.
And tiles don't have those annoying/ugly arrows.

I do need to fix it so the title page is the first page, not the last, though.

**Comment by vyder** [comment]
Apart from UX issues - functionally, the tiles seem to be loading relatively giant images for each 'page' - big enough that for any of the players in our group it takes a good 3-12s for a single page to load. Then if you go to the next page, wait again etc.

The PDF I've linked loads at the start of the game quite quickly along with the other assets - and having duplicate objects seems to cache the PDF just fine. So turning pages on a PDF is quite seamless and performant.


Back to the UX:

With the tiles, don't you have to constantly hold down Alt to read?

The PDF object provides the same number keys for page number, and the mouse wheel to scroll - and well explicit page controls and prev/next buttons.

I'm on a Mac so I can't check the PageUp/Down keys for either object.

Personally, I don't mind the arrows. They aren't that intrusive, and quite useful for players who are not "gamers". If I start getting into UI elements of TTS that bug me, those arrows are way down the priority list imo.

---

Either way - if ultimately you are strongly opposed to adding it in, I can explore creating/hosting a fork.

**Comment by ikegami** [comment]
>  big enough that for any of the players in our group it takes a good 3-12s for a single page to load.

Think of how much faster the game loads, then...

> With the tiles, don't you have to constantly hold down Alt to read?

For full screen yes. Which is good. That means you can easily start reading, and easily stop reading. This is a *plus*.

> The PDF object provides the same number keys for page number,

I was pointing out this wasn't an advantage of PDFs.

> They aren't that intrusive,

They're ugly and the literally cover up text.

**Comment by ikegami** [comment]
I went a gave the PDF a second try, and it's just so hard to use! You have to click on that little square to open it up. (Alt just shows a small image you can't zoom in on.) You have to keep the mouse over the image in full screen mode. or it becomes unreadably transparent. Ok, you can easily dismiss the full screen mode using Esc, which is better than half the dialogs in TTS. Also, it's so dark!

On the flip side, the PDF is more up-to-date. But I could simply make a new tile. And if you scale up the size of the PDF, it also scales it up when using Alt so it doesn't take up just half the screen, saving from having to use full screen mode. And finally, the PDF is 15 MiB while the images 68 MiB. It's still 15 MiB loaded up front by every player instead of 0.1 MiB (the size of the title page).

So maybe the only downsides is that more expensive first time load, and that the PDF is dark. The darkness makes it more depressing, but not necessarily harder to read.

**Comment by vyder** [comment]
Perhaps this is rendering differently for both of us - here's what it looks like for me:

![Screen Shot 2021-01-06 at 5 56 04 PM](https://user-images.githubusercontent.com/587136/103768787-2647b380-5049-11eb-80ab-9e3b06699ea5.png)

I feel like a lot of what you're saying is subjective opinion - and I'm not trying to change your mind on them. I just wanted to solve the page load functional painpoint and so suggested this as a fix.

My group has adopted a version with the PDF rulebook bag as our main game and perhaps I'll make a standalone rulebook bag available on the Workshop this weekend when I find some time. That alone shouldn't be a violation of copyright.
