### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by JolinM** [ikegami/tts_brass#2]
Hi Eric, I was wondering if your code was a fixed script for the package **Brass_ Birmingham [FULLY SCRIPTED] (2040642748).ttsmod**. If not, how do you use it to play the game?

Best!

**Comment by ikegami** [comment]
It is *lightly* scripted. It handles setup and scoring, and it provides money to aid gaining money, spending money and changing income. It's stateless, allowing you to fix problems, undo actions, etc.

You place the .json file in `%UserProfile%\Documents\My Games\Tabletop Simulator\Saves`

**Comment by ikegami** [comment]
I have added these instructions to [`README.md`](https://github.com/ikegami/tts_brass#readme)

**Comment by JolinM** [comment]
Thanks for the quick reply, and the hard work, it looks like a charm to use; eager to try it with some friends :)
